/// Flutter icons MedicalIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MedicalIcons
///      fonts:
///       - asset: fonts/MedicalIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MedicalIcons {
  MedicalIcons._();

  static const _kFontFam = 'MedicalIcons';
  static const String? _kFontPkg = null;

  static const IconData hamburger =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
